### ISSUE TITLE
Build Image for ppc64le and s390x 

### ISSUE THREAD

**Issue by AlstonDias** [pierDipi/sacura#34]
We have a dependency of the sacura image for tests and we need it to be build for ppc64le and s390x.  
I see that this image is build using GitHub Actions. The command building the image is  `ko resolve -f release/image.yaml` but this only build the x86_64 image. 

We could pass the --platform flag to build the images.
` ko resolve -f release/image.yaml --platform=all`  to build for all arches
` ko resolve -f release/image.yaml --platform=ppc64le`  to build for ppc64le
` ko resolve -f release/image.yaml --platform=s390x`  to build for s390x

Could we please add this change in the GitHub Actions script to build Multi-arch images.

**Comment by pierDipi** [comment]
Done in https://github.com/pierDipi/sacura/commit/a2882fb38535781f47709484f2ebbcf0fe9e5d76

**Comment by pierDipi** [comment]
Image published: https://github.com/pierDipi/sacura/pkgs/container/sacura%2Fsacura-7befbbbc92911c6727467cfbf23af88f/108485927?tag=latest
